# Generated by Django 2.1.1 on 2018-09-08 21:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarea1', '0003_auto_20180908_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 8, 21, 57, 49, 268090, tzinfo=utc)),
        ),
    ]
