# Generated by Django 2.1.1 on 2018-09-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea1', '0005_auto_20180908_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default='22:00:39'),
        ),
    ]
