# Generated by Django 2.1.1 on 2018-09-08 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea1', '0006_auto_20180908_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 8, 22, 1, 14, 933204)),
        ),
    ]
